require("nvim-treesitter")
    .install({
        "css",
        "editorconfig",
        "fish",
        "html",
        "javascript",
        "json",
        "nix",
        "rust",
        "toml",
        "yaml",
    })
    :wait()
