# Theme
set-hook -g client-light-theme {
	set -g @bg "#f0edec"
	set -g @bg-status "#f5f5f5"
	set -g @bg-float "#fafafa"
	set -g @bg-highlight "#ebebeb"
	set -g @bg-selection "#c9cbd1"
	set -g @bg-match "#b5cbd2"
	set -g @fg "#545464"
	set -g @fg-secondary "#8a8980"
	set -g @fg-alert "#6f894e"
	set -g @border "#c0c0c0"
}

set-hook -g client-dark-theme {
	set -g @bg "#1c1917"
	set -g @bg-status "#282727"
	set -g @bg-float "#0d0c0c"
	set -g @bg-highlight "#393836"
	set -g @bg-selection "#223249"
	set -g @bg-match "#2d4f67"
	set -g @fg "#c5c9c5"
	set -g @fg-secondary "#737c73"
	set -g @fg-alert "#87a987"
	set -g @border "#625e5a"
}

# Prefix
set -g prefix C-j
bind C-j send-prefix
unbind C-b

# Settings
set -g mouse on
set -g set-titles on
set -g set-clipboard on
set -g focus-events on
set -g renumber-windows on
set -g detach-on-destroy off
set -g base-index 1
set -g pane-base-index 1
set -g history-limit 1000000

# Command prompt
set -g status-keys vi
set -g cursor-style block
set -g prompt-cursor-style bar
# set -g prompt-command-cursor-style block

# Menu
set -g menu-border-lines single

# Copy mode
set -g mode-keys vi
set -g mode-style "bg=#{@bg-highlight} fg=#{@fg}"
set -g copy-mode-selection-style "bg=#{@bg-selection} fg=#{@fg}"
set -g copy-mode-match-style "bg=#{@bg-match} fg=#{@fg}"
set -g copy-mode-current-match-style "bg=#{@bg-match} fg=#{@fg} bold"
set -g copy-mode-mark-style "bg=#{@bg-highlight} fg=#{@fg}"
set -g copy-mode-position-format "\
#[align=right] \
#{t/p:top_line_time}\
#{?#{e|>:#{top_line_time},0}, ,}\
[#{scroll_position}/#{history_size}]\
#{?search_timed_out, (timed out),}\
#{?search_count, (#{search_count}#{?search_count_partial,+,} results),}\
 "
set -g copy-mode-position-style "bg=#{@bg-highlight} fg=#{@fg}"
bind -T copy-mode-vi [ send-keys -X previous-prompt
bind -T copy-mode-vi ] send-keys -X next-prompt

# Popup windows
set -g popup-border-lines single

# Status line
set -g status-position top
set -g status-style "bg=#{@bg-status} fg=#{@fg}"
set -g status-left " "
set -g status-left-length 50
set -g status-right "#{?#{!=:#{client_key_table},root},[#{client_key_table}],} "
set -g status-right-length 50
set -g window-status-separator " "
set -g window-status-format "#{?window_marked_flag,#[bold],}#{?window_zoomed_flag,#[italics],}#I:#W"
set -g window-status-current-format "#{?window_marked_flag,#[bold],}#{?window_zoomed_flag,#[italics],}#I:#W"
set -g window-status-style "fg=#{@fg-secondary}"
set -g window-status-current-style "fg=#{@fg}"
set -g window-status-bell-style "fg=#{@fg-alert}"
set -g window-status-activity-style "fg=#{@fg-alert}"
bind b set -g status
